# Generated by Django 6.0.4 on 2026-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(unique=True, verbose_name="題號"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="題名")),
                ("title_slug", models.SlugField(max_length=255)),
                ("url", models.URLField(verbose_name="網址")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=8,
                        verbose_name="難度",
                    ),
                ),
                (
                    "ac_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="通過率(%)"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="problems", to="problems.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
    ]
