# Generated by Django 6.0.4 on 2026-08-06 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP 主機"
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(default=587, verbose_name="連接埠"),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=255, verbose_name="帳號"),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=255, verbose_name="密碼"),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="使用 TLS")),
                (
                    "from_email",
                    models.CharField(
                        blank=True,
                        help_text="例如：LeetCode 教學管理系統 <noreply@example.com>",
                        max_length=255,
                        verbose_name="寄件者顯示",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email 設定",
                "verbose_name_plural": "Email 設定",
            },
        ),
    ]
